publisher:
  name: Oridion
  website: https://oridion.xyz
  email: oridion.xyz@gmail.com
app:
  name: SKRAMBL
  address: ''
  android_package: com.oridion.skrambl 
  urls:
    license_url: https://oridion.xyz/license
    copyright_url: https://oridion.xyz/copyright
    privacy_policy_url: https://oridion.xyz/privacy
    website: https://oridion.xyz
  media:
    - purpose: icon
      uri: media/icon-512.png
release:
  address: ''
  media:
    - purpose: icon
      uri: media/icon-512.png
    - purpose: banner
      uri: media/banner-1200x600.png
    - purpose: featureGraphic
      uri: media/feature-1200x1200.png
    - purpose: screenshot
      uri: media/screenshot-01.png
    - purpose: screenshot
      uri: media/screenshot-02.png
    - purpose: screenshot
      uri: media/screenshot-03.png
    - purpose: screenshot
      uri: media/screenshot-04.png
    - purpose: screenshot
      uri: media/screenshot-05.png
    - purpose: screenshot
      uri: media/screenshot-06.png
    - purpose: screenshot
      uri: media/screenshot-07.png
    - purpose: screenshot
      uri: media/screenshot-08.png
  files:
    - purpose: install
      uri: build/app/outputs/flutter-apk/app-release.apk
  catalog:
    en-US:
      name: SKRAMBL
      short_description: "Send SOL with added obfuscation and control."
      long_description: "SKRAMBL lets you send SOL through obfuscated transaction paths with optional delays, making transfers harder to trace while keeping the experience simple and user-friendly. Powered by Oridion."
      new_in_version: "Initial release of SKRAMBL for Seeker."
      saga_features: "Secure transaction signing with Seed Vault."
solana_mobile_dapp_publisher_portal:
  google_store_package: com.oridion.skrambl
  testing_instructions: |
    1. Install the release APK.
    2. Open SKRAMBL and create a parent wallet (Seed Vault required).
    3. Fund wallet with SOL.
    4. Test sending a standard transfer and a SKRAMBLED transfer with delay.
